### ISSUE TITLE
CryoSPARC

### ISSUE THREAD

**Issue by anmugo** [ubccr/software-layer#100]
I am requesting you install the above software.

https://guide.cryosparc.com/setup-configuration-and-management/how-to-download-install-and-configure/downloading-and-installing-cryosparc

**Comment by dsajdak** [comment]
@anmugo There is no Easybuild recipe available for this software and due to staffing constraints that would normally put it at the bottom of our to-do list.  However, we specifically discussed this at a recent staff meeting and do not think it is something that can be effectively setup in a central location for all users.   First, it requires the user to agree to a license agreement and CCR no longer does this on behalf of users.  Anything that requires a license must be installed in the group's project directory.  Second, it requires user accounts and a database to run which is not ideal in our HPC environment and not something we'd setup to share with all users.  This would have to be something done in the group's project directory.  Third, it requires the master node to be running all the time, or at least during the job, and we do not allow processes running on our login nodes for that long.  There are other concerns as well and ways around some of these issues but to set this up would be a project CCR staff can not commit to at this time.  This is something your group would have to work through on it's own.
