### ISSUE TITLE
HapDup

### ISSUE THREAD

**Issue by luanelandau** [ubccr/software-layer#101]
Hello, 

I tried using this software with singularity but I was not successful in doing so and couldn't solve the issue. It will be very helpful for me to phase the assemblies I've been working with. 

https://github.com/KolmogorovLab/hapdup

Thank you so much in advance.

**Comment by tonykew** [comment]
There is no EasyBuild easyconfig file for hapdup
hapdup has multiple dependencies that in turn have dependencies.
hapdup uses Margin which uses sonLib.  I can't get the tests to pass
for the sonLib library - it fails with a unicode decode error

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 24: invalid start byte`

This should be easier to run with singularity than to build & there
are examples provided on the website

something like:

export SINGULARITY_CACHEDIR="/projects/academic/cl243/singlularity"
export SINGULARITY_LOCALCACHEDIR="${SINGULARITY_CACHEDIR}/cache"
export SINGULARITY_TMPDIR="${SINGULARITY_CACHEDIR}/tmp"
export APPTAINER_CACHEDIR="${SINGULARITY_CACHEDIR}"
export APPTAINER_TMPDIR="$(SINGULARITY_TMPDIR)"
singularity exec \
 --bind /cvmfs:/cvmfs:ro \
 --bind /util:/util:ro \
 --bind /vscratch:/vscratch \
 --bind /projects:/projects \
 --bind /scratch:/scratch \
 docker://mkolmogo/hapdup:0.12 \
 hapdup \
 --assembly /path/to/assembly.fasta \
 --bam /path/to/lr_mapping.bam \
 --out-dir /path/to/output/dir \
 -t $(SLURM_NTASKS:-16} \
 --rtype ont


For PacBio HiFi input, use "--rtype hifi" instead of "--rtype ont" for the final line

Note that this is untested but should work.
