### ISSUE TITLE
ROOT (CERN) 

### ISSUE THREAD

**Issue by rupulchandna** [ubccr/software-layer#108]
Hey,

I've been trying to install ROOT (https://root.cern/) on CCR, but running into some dependency issues. 
Given its widespread use in the particle physics community, can we install it as a module for everyone?

Thanks
Rupul

**Comment by tonykew** [comment]
Dear Rupul,

There is a docker image available, and this can be run on our systems with
singularity e.g.

$ singularity run docker://rootproject/root:latest

Since this is an interactive tool that can produce graphs, this could be run on CCR's
OnDemand - see: https://docs.ccr.buffalo.edu/en/latest/portals/ood/

 I will, however, look at building this for our software stack

Tony
