### ISSUE TITLE
OpenSees

### ISSUE THREAD

**Issue by alirezak1991** [ubccr/software-layer#256]
Dear UB CCR staff,

My name is Alireza Kazemian, and I am a Ph.D. candidate, soon defending my Ph.D.
I need to have access to "OpenSees", which is a structural analysis software, however, this software is not available on CCR anymore (it used to be available three years ago, which I used last time). Can you please install this software as soon as you can?
I need to defend my dissertation by mid-May; it is very urgent.

I really appreciate any help you can provide.

Best regards,
Alireza Kazemian

**Comment by dsajdak** [comment]
Hi @alirezak1991 While we can install the software, we can't guarantee it will be done on an urgent basis.  We don't have any idea how difficult this will be and our software installations are being done as we have time around other work.  Since you used this before on our systems, I'd recommend you go back to using the legacy software as the OpenSees software you previously used is still in that software release.  [See here ](https://docs.ccr.buffalo.edu/en/latest/howto/newenv/#how-to-use-the-legacy-software)for more info.  I will leave this issue open though because we anticipate there are others using this software that just haven't requested it yet.

**Comment by aebruno** [comment]
OpenSees is now available. To use run: `module load intel opensees/3.2.0-Python-3.9.6-parallel`
