### ISSUE TITLE
Download gotcloud to use VCFcooker

### ISSUE THREAD

**Issue by rmn8** [ubccr/software-layer#283]
I would like to install  gotcloud. Below is the installaltion
https://genome.sph.umich.edu/wiki/GotCloud#Install_GotCloud_Software

**Comment by dsajdak** [comment]
@rmn8 there is no Easybuild recipe available for this software and due to staffing constraints I don't expect our team to have the time to build a recipe in the near future.  If you'd like to try installing this yourself in your group's project directory, you should follow the instructions for installing from source.

**Comment by rmn8** [comment]
Hi , I was wondering how to go about that?
Thanks
