### ISSUE TITLE
PySyft Library

### ISSUE THREAD

**Issue by Abhidragneel** [ubccr/software-layer#33]
I, Abhijith G. Anil, (CCR Username: abhijit3) am currently working with Dr. Haimonti Dutta on a Federated Learning project which requires PySyft library, currently unavailable on the CCR. Hence I request access to said library.

**Comment by aebruno** [comment]
@Abhidragneel please provide the URL to the software.

**Comment by Abhidragneel** [comment]
https://pypi.org/project/syft/

**Comment by Haimonti** [comment]
@aebruno Thanks for looking into this! Do you have a sense by what time this software may be installed on the server? Many thanks for the help with this.

**Comment by aebruno** [comment]
@Haimonti unfortunately, we can't provide any time estimates. In the mean time you're welcome to try installing this yourself. Might be worth trying this out in your own python virtual environment.

**Comment by sguerciojr** [comment]
@Haimonti,

Have you had a chance to try and install this package yet? It seems like a pretty straight forward pip install from within a Python Virtual environment. However, depending on how you plan to use it, it might not work on our HPC platform because we do not allow users to open ports and run server type applications on the cluster.

If you are only looking to use the client part of this, then it would be able to connect out.

We have documentation on python virtual environments on our docs page:

https://docs.ccr.buffalo.edu/en/latest/howto/python/#python-virtual-environments

If you need help with that, submit a freshdesk ticket and we can work with you on the help desk portal.

Thank you,

Sam
