### ISSUE TITLE
karateclub 

### ISSUE THREAD

**Issue by atul1234anand** [ubccr/software-layer#360]
Could you please install karateclub. I am not sure what the current version is, but the Git Repository for the software can be found [here](https://github.com/benedekrozemberczki/karateclub.git).

**Comment by dsajdak** [comment]
@atul1234anand There is no Easybuild recipe for this and the dependencies do not match what is currently supported in our latest software release so it is not something we can commit to installing.  Since this is a python based package, you could try building an Easybuild Python bundle recipe as described in our [documentation](https://docs.ccr.buffalo.edu/en/latest/software/modules/#python).  See also [here](https://docs.ccr.buffalo.edu/en/latest/software/building/) and [here](https://docs.ccr.buffalo.edu/en/latest/howto/easybuild/) for more Easybuild information.  Alternatively, this may work in a virtual environment - see [here](https://docs.ccr.buffalo.edu/en/latest/howto/python/#virtual-environments) for more info.
