### ISSUE TITLE
Installing FSL on CCR module

### ISSUE THREAD

**Issue by sarahmuldoon** [ubccr/software-layer#53]
Hello,
My group uses the FSL software package to process neuroimaging data.  It was installed for us in the old software environment and we would like to request it to be installed in the new software module so that we can continue to use it.

Installation info: https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation

Thank you so much and let me know if you have any questions.
Sarah Muldoon

**Comment by dsajdak** [comment]
Hi @sarahmuldoon our apologies for the severe delaying in responding to your request.  I have spent a full 10 days on attempting to install this software and ultimately was unsuccessful.  FSL tools have many complex dependencies and those have their own dependencies.  Despite working my way through all of those EasyBuild installations successfully, FSL did not build correctly.  I did more research on it and came across several interesting things.  The first is [this conversation]([https://github.com/easybuilders/easybuild-easyconfigs/issues/7899]) on the EasyBuild repo - not all is relevant to our installation attempt but some of the newer comments are.  Specifically this comment:

"Using eb it is impossible to install FSL v6.0.4, see my [post on the FSL mailinglist](https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2103&L=FSL&O=D&P=115545). Basically, every new version apparently needs new patches. This is particularly hard to work out at times, because the distribution ships libraries sometimes even in two copies, which are incompatible. Even, if this is sorted out, there are undefined references and the FSL maintainers do not name all dependencies. Some necessary patches indicate, that one unknown machine satisfies all dependencies ('home' in include paths)."

The second, is that link to the user's post on the FSL mailing list.  He was never replied to despite valid concerns and requests.  You may want to contact them to add your voice to the request that they provide a useful source for HPC centers to compile against.

Ultimately, our issues are that the source code is not available, there are embedded paths in the scripts they provide that can't be changed, and it's very difficult to see what part of the installation is failing.  I just get a "build projects failed.  Check build log" which says the same thing.  I looked back at CCR's previous build of FSL tools and have found similar issues and I wonder how it ever worked.  However, it's possible the person who did the install manually hacked it to work.  In order to maintain our software repository we do need to install software with EasyBuild recipes and in this case, it's not possible at this time.  A developer at Compute Canada has a work around that he shared but it is based on an older version that we can no longer download.  So until they update their software and EB recipe, I don't see us being able to complete this installation.

We are working on building some of the dependencies though and will publish those as modules.  This will allow your group to install this manually in your project directory without using an EasyBuild recipe but using CCR's core software modules for compilers and dependencies.
