### ISSUE TITLE
Tmux 3.3a

### ISSUE THREAD

**Issue by scottdoy** [ubccr/software-layer#59]
Tmux is essential for working via command line or ssh. Updated versions of Tmux have several features (like plugins) that facilitate a fast and efficient workflow.

Tmux 3.3a is available in the EasyBuild catalog here: https://github.com/easybuilders/easybuild-easyconfigs/tree/develop/easybuild/easyconfigs/t/tmux

**Comment by sguerciojr** [comment]
Scott, Tmux should be available in the new software environment. You need to use the new ccr modules. 
See here: https://docs.ccr.buffalo.edu/en/latest/howto/newenv/#ccrs-new-environment-explained

Note, not everything is available because we are working on building it out. /util is 20 years worth of build so we have a lot to do :)

**Comment by aebruno** [comment]
tmux is also available on the login nodes
